from pathlib import Path
import subprocess,re,sys
root=Path(__file__).resolve().parents[1]; out=[]
def ck(name,cond): out.append((name,bool(cond)))
# Skills 9-17: definition, version, locked = 27
skills=[('9','traceability','SKILL.md'),('10','blueprint-generator','SKILL.md'),('11','implementation-readiness','SKILL.md'),('12','implementation','implementation-SKILL-v1.0.md'),('13','implementation-plan','SKILL.md'),('14','implementation-validator','SKILL.md'),('15','implementation-executor','SKILL.md'),('16','implementation-verification','SKILL.md'),('17','implementation-closure','SKILL.md')]
for n,f,fn in skills:
 p=root/'.codex/BA contrains'/f/fn; ck(f'Skill {n} definition exists',p.exists()); t=p.read_text(errors='ignore') if p.exists() else ''; ck(f'Skill {n} version 1.0', bool(re.search(r'(?:Version|version)[^\n]*1\.0',t))); ck(f'Skill {n} locked', 'LOCKED' in t)
# 16 core artifacts
arts=['projects/self-storage/e2e/PHASE-3.md','projects/self-storage/e2e/BA-baseline-index.md','projects/self-storage/implementation-readiness/implementation-readiness.md','projects/self-storage/implementation/implementation-scope.md','projects/self-storage/implementation/implementation.md','projects/self-storage/implementation-plan/implementation-plan.md','projects/self-storage/implementation-validator/implementation-plan-validation.md','projects/self-storage/implementation-executor/execution-record-phase3.md','projects/self-storage/implementation-verification/verification-record-phase3.md','projects/self-storage/closure/closure-record-phase3.md','projects/regression/phase3-regression.md','projects/self-storage/implementation-traceability/implementation-traceability-matrix.md','projects/self-storage/demo-approval/demo-scope.md','projects/self-storage/implementation-demo/index.html','projects/self-storage/implementation-demo/app.js','projects/self-storage/implementation-demo/styles.css']
for a in arts: ck('artifact exists: '+a,(root/a).exists())
# 4 master state checks =47
p=(root/arts[0]).read_text(); ck('PHASE-3 status COMPLETE','**Status:** `COMPLETE`' in p); ck('PHASE-3 regression PASS','FULL FRAMEWORK REGRESSION: PASS' in p); ck('PHASE-3 production BLOCKED','PRODUCTION SCOPE: BLOCKED' in p); ck('PHASE-3 demo CLOSED_WITH_GAPS','DEMO SCOPE: CLOSED_WITH_GAPS' in p)
# 10 lifecycle state checks =57
impl=(root/'projects/self-storage/implementation/implementation.md').read_text(); scope=(root/'projects/self-storage/implementation/implementation-scope.md').read_text(); plan=(root/'projects/self-storage/implementation-plan/implementation-plan.md').read_text(); val=(root/'projects/self-storage/implementation-validator/implementation-plan-validation.md').read_text(); exe=(root/'projects/self-storage/implementation-executor/execution-record-phase3.md').read_text(); ver=(root/'projects/self-storage/implementation-verification/verification-record-phase3.md').read_text(); clo=(root/'projects/self-storage/closure/closure-record-phase3.md').read_text(); reg=(root/'projects/regression/phase3-regression.md').read_text();
checks=[('implementation demo completed','Demo implementation:** `COMPLETED`' in impl),('implementation production blocked','Production readiness:** `BLOCKED`' in impl),('scope has two demo IDs',all(x in scope for x in ['IMP-SS-DEMO-001','IMP-SS-DEMO-002'])),('plan two items completed',all(x in plan for x in ['IP-SS-DEMO-001','IP-SS-DEMO-002','COMPLETED'])),('validator overall pass with open items','PASS WITH OPEN ITEMS' in val),('executor no action','NO_ACTION' in exe),('executor no production execution','No production implementation was executed.' in exe),('verification demo 1 verified','IP-SS-DEMO-001' in ver and 'VERIFIED / PASS' in ver),('verification demo 2 verified','IP-SS-DEMO-002' in ver and 'VERIFIED / PASS' in ver),('closure overall closed with gaps','CLOSED_WITH_GAPS' in clo)]
for n,c in checks: ck(n,c)
# 10 traceability/boundary checks=67
ck('traceability matrix includes demo 1','IMP-SS-DEMO-001' in (root/'projects/self-storage/implementation-traceability/implementation-traceability-matrix.md').read_text()); ck('traceability matrix includes demo 2','IMP-SS-DEMO-002' in (root/'projects/self-storage/implementation-traceability/implementation-traceability-matrix.md').read_text()); ck('traceability matrix PASS','IMPLEMENTATION TRACEABILITY: PASS' in (root/'projects/self-storage/implementation-traceability/implementation-traceability-matrix.md').read_text()); ck('demo approval is non-production','Non-production demo' in (root/'projects/self-storage/demo-approval/demo-scope.md').read_text()); ck('demo approval excludes payment','No production payment' in (root/'projects/self-storage/demo-approval/demo-scope.md').read_text()); ck('demo approval technical decision plain html','plain HTML, CSS, and JavaScript' in (root/'projects/self-storage/demo-approval/demo-scope.md').read_text()); ck('implementation explicitly excludes databases','databases' in impl and 'does not implement' in impl); ck('verification production not verified','BLOCKED / NOT VERIFIED' in ver); ck('closure production not closed','BLOCKED / NOT CLOSED' in clo); ck('regression record contains actual pass','Actual result:' in reg and 'PASS' in reg)
# 11 history + phase1/2/git checks =78
history=['projects/self-storage/e2e-lifecycle-report-r2.md','projects/self-storage/implementation/implementation-r2.md','projects/self-storage/implementation-readiness/implementation-readiness-r2.md','projects/self-storage/implementation-plan/implementation-plan-r2.md','projects/self-storage/implementation-validator/implementation-plan-validation-r2.md','projects/self-storage/implementation-executor/execution-record-r2.md','projects/self-storage/implementation-verification/verification-result-r2.md','projects/self-storage/implementation-closure/closure-result-r2.md']
for h in history: ck('history preserved: '+h,(root/h).exists())
# 3 more
ck('phase2 governance document exists',(root/'governance/PHASE-2.md').exists())
ck('phase1 foundation commit exists', subprocess.run(['git','-C',str(root),'cat-file','-e','99cf6fb^{commit}'],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0)
log=subprocess.check_output(['git','-C',str(root),'log','--oneline','--all'],text=True); ck('phase3 merge chain #4-#11 present',all(f'Merge pull request #{i}' in log for i in range(4,12)))
print('TOTAL',len(out)); print('PASS',sum(c for _,c in out)); print('FAIL',sum(not c for _,c in out));
for n,c in out: print(('PASS ' if c else 'FAIL ')+n)
sys.exit(0 if all(c for _,c in out) else 1)
